### ISSUE TITLE
BrowseFragment has no new instance class (not singleton)

### ISSUE THREAD

**Issue by shawnyxie** [williamxu/MangoReader#68]

**Comment by ckmah** [comment]
same holds for LibraryFragment

**Comment by akrolsmir** [comment]
Oh, this would probably reduce the user perceived lag -- if we could use a cached singleton for BrowseFragment, then we wouldn't have to do a network call taking 3-10 seconds every time the user switches between Browse and Library.

Increasing the priority.

**Comment by ckmah** [comment]
@williamxu suggests alternatives such as caching json results or pagination of some kind

**Comment by akrolsmir** [comment]
JSON results are already cached, the problem (I think) I'm running into is that even after being cached the jsons still take too long to parse.

Pagination might work for "recently updated" but not for popularity, due to the API calls available to us atm.

My suggesting would be a placeholder loading screen -- see #55.

**Comment by ckmah** [comment]
closing this issue if we agree on the placeholder loading screen a la detailsfragment placeholder
